using UnityEngine;

// Represent logic of all particles of spells and attacks, generated by attacker towards target
public class Particle : MonoBehaviour
{
    public float speed; // Moving speed of particles
    private GameObject target;
    private float attack;
    private bool onInit = false;
    public void Init(GameObject target, float attack)
    {
        this.target = target;
        this.attack = attack;
        onInit = true;
    }

    private void FixedUpdate()
    {
        if (onInit)
        {
            try
            {
                // Move towards the target each frame and adjust rotation
                transform.position += (target.transform.position - transform.position).normalized * speed * Time.deltaTime;
                // TODO: rotation not working
                transform.rotation = Quaternion.Euler(target.transform.position - transform.position).normalized;
            }
            catch
            {
                // In case that target is destroyed already, destroy self
                Destroy(gameObject);
            }
        }
    }

    // On target hit destroy self
    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.gameObject.Equals(target))
        {
            target.GetComponent<Combat>().GetHit(this.attack);
            Destroy(gameObject);
        }
    }
}
